Synthetic Graph Data Generator
capitalone/synthetic-data pull request #267
Opened 2022-08-11 17:17 UTC by MisterPNP

- add synthetic graph data generator
- add example notebook+data
- add tests for graph data generator

2022-08-11 17:17 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/capitalone/synthetic-data?pullRequest=267) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/capitalone/synthetic-data?pullRequest=267) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: MisterPNP<br/>:x: Pierre-Nicolas<br/><hr/>**Pierre-Nicolas** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/capitalone/synthetic-data?pullRequest=267) it.</sub>

2022-08-12 17:13 UTC, taylorfturner requested changes

2022-08-12 17:13 UTC, taylorfturner commented on synthetic_data/graph_synthetic_data.py
> +class GraphDataGenerator():
```suggestion
class GraphDataGenerator(object):
```

2022-08-12 17:13 UTC, taylorfturner commented on synthetic_data/graph_synthetic_data.py
> +    Synthesize graph data from a GraphProfiler or graph profile.
```suggestion
    Synthesize graph data from a graph profile object
```

2022-08-12 17:13 UTC, taylorfturner commented on synthetic_data/graph_synthetic_data.py
> +    graph_profile: GraphProfiler object/graph_profile
what's the difference between the two?

2022-08-12 17:13 UTC, taylorfturner commented on synthetic_data/graph_synthetic_data.py
> +    def __init__(self, graph):
although..l as I read `L26-L34` maybe we shouldn't change

2022-08-12 17:13 UTC, taylorfturner commented on tests/test_graph_synthetic.py
> +    @classmethod
add new line for break

2022-08-12 17:13 UTC, taylorfturner commented on tests/test_graph_synthetic.py
> +    unittest.main()
new line EOF

2022-08-12 17:13 UTC, taylorfturner commented on tests/test_graph_synthetic.py
> +        self.assertTrue(True)
is this asserting the `plt` renders without error?

2022-08-12 17:13 UTC, taylorfturner commented on synthetic_data/graph_synthetic_data.py
> +                    edge_attributes[categorical_attribute] = sample
we can condense this into one `for` loop. loop over a list of the variables and then in the nested `for` loop, loop over the contents of the respective variable 
```
for attribute in [continuous_attribute, categorical_attribute]:
> for value in attribute:
...
```

2022-08-12 18:49 UTC, taylorfturner approved these changes

2022-08-12 20:31 UTC, tazitoo approved these changes

2022-08-12 20:32 UTC, merged