git ignore and rm DSstore
capitalone/synthetic-data pull request #291
Opened 2023-07-08 00:17 UTC by drahc1R

2023-07-08 00:20 UTC, taylorfturner requested changes

2023-07-08 00:20 UTC, taylorfturner commented on .gitignore
> +**/.DS_Store
can we avoid having two lines here? 162 is what we have for `dataprofiler` but do we have to have the `.DS_Store` too?

2023-07-08 00:24 UTC, taylorfturner commented on .gitignore
> +**/.DS_Store
actually I might be mistaken .... I think you just need line 162 here based on the git documentation [here](https://git-scm.com/docs/gitignore#:~:text=A%20leading%20%22**%22%20followed%20by%20a%20slash%20means%20match%20in%20all%20directories.%20For%20example%2C%20%22**/foo%22%20matches%20file%20or%20directory%20%22foo%22%20anywhere%2C%20the%20same%20as%20pattern%20%22foo%22.%20%22**/foo/bar%22%20matches%20file%20or%20directory%20%22bar%22%20anywhere%20that%20is%20directly%20under%20directory%20%22foo%22.)

2023-07-08 00:43 UTC, taylorfturner requested changes

2023-07-08 00:43 UTC, taylorfturner commented on .gitignore
> +.DS_Store
```suggestion
```

2023-07-10 13:42 UTC, taylorfturner approved these changes

2023-07-10 13:46 UTC, JGSweets approved these changes

2023-07-10 13:48 UTC, merged