Categorical generator and tests
capitalone/synthetic-data pull request #296
Opened 2023-07-12 19:56 UTC by lizlouise1335

Generator file and test file for category subset generator

2023-07-12 20:08 UTC, JGSweets commented on tests/test_categorical_generator.py
> +        result = random_categorical(self.rng, num_rows = 5)
let's make sure to test at least two variation of num_rows to ensure functionality

2023-07-12 20:08 UTC, JGSweets commented on tests/test_categorical_generator.py
> +from synthetic_data.dataset_generators.categorical_generator import random_categorical
should be a space between first party (synthetic_data) imports and third party

2023-07-12 20:08 UTC, JGSweets commented on tests/test_categorical_generator.py
> +import numpy as np
need a space between built-in and third party libraries

2023-07-12 20:14 UTC, JGSweets commented on synthetic_data/dataset_generators/categorical_generator.py
> +import numpy as np
let's move this into `distinct_generators` and move the previous.

Also, let's make sure the tests follow the same folder structure as well.

2023-07-12 20:38 UTC, JGSweets commented on synthetic_data/dataset_generators/categorical_generator.py
> +import numpy as np
The folder should be there now that #293 merged.

2023-07-13 14:54 UTC, JGSweets submitted a review, later dismissed

2023-07-13 17:34 UTC, taylorfturner requested changes

2023-07-13 17:34 UTC, taylorfturner commented on synthetic_data/distinct_generators/categorical_generator.py
> +        categories = ["A", "B", "C", "D", "E"]
thinking this should be the default for the parameter....

2023-07-13 17:41 UTC, taylorfturner requested changes

2023-07-13 17:41 UTC, taylorfturner commented on synthetic_data/distinct_generators/categorical_generator.py
> +        categories = ["A", "B", "C", "D", "E"]
mutable... nevermind

2023-07-13 17:42 UTC, taylorfturner approved these changes

2023-07-13 17:55 UTC, merged