text/string generators become one + removing to_csv from dataset_generator
capitalone/synthetic-data pull request #317
Opened 2023-07-27 14:17 UTC by lizlouise1335

- text and string generators are now just one overarching string generator 
- all files affected by this change have been remedied 
- to_csv has been removed from dataset_generator
- testing files have been updated to reflect all above changes

2023-07-27 20:28 UTC, taylorfturner requested changes

2023-07-27 20:28 UTC, taylorfturner commented on synthetic_data/dataset_generator.py
> +from synthetic_data.distinct_generators.text_generator import random_string
nice

2023-07-27 20:28 UTC, taylorfturner commented on synthetic_data/dataset_generator.py
> -    path: Optional[str] = None,
nice

2023-07-27 20:28 UTC, taylorfturner commented on tests/test_dataset_generator.py
> -                    "1011110011100011010010100011101001000100100010111101001100001000010001000101001100011100100001111001000100100110100111110001010011101110011110000110110110111111001010101101111001
so beautiful ❤️

2023-07-27 20:28 UTC, taylorfturner commented on tests/test_dataset_generator.py
> +            print(list(df[blah]))
yikes ☠️

2023-07-27 20:28 UTC, taylorfturner commented on tests/test_dataset_generator.py
> +            print(list(df[blah]))
😂

2023-07-27 20:28 UTC, taylorfturner commented on synthetic_data/distinct_generators/text_generator.py
> +    str_len_max: int = 1000,
I think we should clarify the docstring so its clear the value here is one above the largest per the [docs](https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.integers.html#:~:text=If%20provided%2C%20one%20above%20the%20largest%20(signed)%20integer%20to%20be%20drawn%20from%20the%20distribution%20(see%20above%20for%20behavior%20if%20high%3DNone).%20If%20array%2Dlike%2C%20must%20contain%20integer%20values)

2023-07-28 17:41 UTC, taylorfturner requested changes

2023-07-28 17:41 UTC, taylorfturner commented on tests/distinct_generators/test_text_generator.py
>  class TestTextGeneratorFunctions(unittest.TestCase):
rename

2023-07-28 17:41 UTC, taylorfturner commented on tests/distinct_generators/test_text_generator.py
rename file

2023-07-28 17:53 UTC, taylorfturner commented on synthetic_data/dataset_generator.py
>          "string": random_string,
and its `string` here

2023-07-28 18:00 UTC, taylorfturner approved these changes

2023-07-28 18:03 UTC, JGSweets commented on tests/test_dataset_generator.py
> -                    "0101000110100010000011000000011111011111111101100010111011000010100001001011000010101010001000101010101010110001100101101100000111010010111011100110100000111110100011000000001100
love this removal

2023-07-28 18:03 UTC, JGSweets commented on tests/test_dataset_generator.py
> +                ["10", "0001", "0100", "10", "000", "100", "00", "01", "1110", "1111"]
changing bc string isn't as long

2023-07-28 18:04 UTC, JGSweets commented on tests/distinct_generators/test_text_generator.py
> -import unittest
would suggest doing text over string bc it matches DP

2023-07-28 18:04 UTC, JGSweets approved these changes

2023-07-28 18:11 UTC, merged