publish-python-package.yml addition
capitalone/synthetic-data pull request #320
Opened 2023-07-27 20:19 UTC by lizlouise1335

new publish yaml

2023-07-27 21:25 UTC, taylorfturner commented
changed base to `feature/python_deploy`

2023-07-27 21:27 UTC, taylorfturner requested changes
blocking until configs on backend are setup -- otherwise LGTM

2023-07-27 21:27 UTC, taylorfturner commented on .github/workflows/publish-python-package.yml
> +        TWINE_REPOSITORY: pypi
this will require some configs

2023-07-27 21:27 UTC, taylorfturner commented on .github/workflows/publish-python-package.yml
> +        TWINE_REPOSITORY: pypi
otherwise LGTM

2023-07-28 19:32 UTC, taylorfturner approved these changes
LGTM

2023-07-28 20:50 UTC, taylorfturner approved these changes

2023-07-28 20:50 UTC, taylorfturner commented on .github/workflows/publish-python-package.yml
mimic of https://github.com/capitalone/DataProfiler/blob/main/.github/workflows/publish-python-package.yml almost

2023-07-28 20:52 UTC, danielbarcklow approved these changes

2023-07-28 20:52 UTC, merged