integrate datetime_generator and get_ordered_col
capitalone/synthetic-data pull request #323
Opened 2023-07-31 15:08 UTC by drahc1R

Replacement to PR https://github.com/capitalone/synthetic-data/pull/318
Integrated get_ordered_columns into dataset_generator.
Reimplemented datetime_generator to work with get_ordered_column.
Implemented unit and integration tests.

2023-07-31 16:44 UTC, taylorfturner requested changes

2023-07-31 16:44 UTC, taylorfturner commented on tests/test_dataset_generator.py
> +from synthetic_data.distinct_generators import datetime_generator as dategen
alias could be a bit more descriptive variable name

2023-07-31 16:44 UTC, taylorfturner commented on tests/test_dataset_generator.py
> +        ordered_data = np.array(
```suggestion
        expected = np.array(
```

2023-07-31 16:44 UTC, taylorfturner commented on tests/test_dataset_generator.py
> +        ordered_data = np.array(
will need to update references to this too

2023-07-31 16:44 UTC, taylorfturner commented on tests/test_dataset_generator.py
> +        ordered_data = np.array(
`expected` and `actual` make it super clear what they are doing

2023-07-31 16:44 UTC, taylorfturner commented on tests/test_dataset_generator.py
> +        output_data = dg.get_ordered_column(data, "datetime", "ascending")
```suggestion
        actual = dg.get_ordered_column(data, "datetime", "ascending")
```

2023-07-31 16:44 UTC, taylorfturner commented on tests/test_dataset_generator.py
> +        ordered_data = np.array(
```suggestion
        expected = np.array(
```

2023-07-31 16:44 UTC, taylorfturner commented on tests/test_dataset_generator.py
> +        output_data = dg.get_ordered_column(data, "datetime", "descending")
```suggestion
        actual = dg.get_ordered_column(data, "datetime", "descending")
```

2023-07-31 16:44 UTC, taylorfturner commented on tests/test_dataset_generator.py
> +        ordered_data = ordered_data[:, 0]
probably don't need this.... can just call `ordered_data[:,0]` in `assert_array_equal`

2023-07-31 16:44 UTC, taylorfturner commented on tests/test_dataset_generator.py
> +        custom_date_format = ["%Y %m %d"]
we should probably have multiple values here ... to validate it processes correctly if it is more than one value in the list

2023-07-31 16:44 UTC, taylorfturner commented on tests/test_dataset_generator.py
> +            output_data.append(dg.get_ordered_column(data[data_type], data_type))
why not call `generate_dataset`?

2023-07-31 16:44 UTC, taylorfturner commented on tests/test_dataset_generator.py
> +        ordered_data = [
expected?

2023-07-31 16:44 UTC, taylorfturner commented on tests/test_dataset_generator.py
> +        data = OrderedDict(
expected?

2023-07-31 16:44 UTC, taylorfturner commented on tests/test_dataset_generator.py
> +    def test_get_ordered_column(self):
add to `TestDatasetGenerator`

2023-07-31 20:55 UTC, taylorfturner requested changes

2023-07-31 20:55 UTC, taylorfturner commented on tests/test_dataset_generator.py
> +
remove

2023-07-31 21:08 UTC, taylorfturner commented on tests/distinct_generators/test_datetime_generator.py
> +        outputs = [
expected

2023-07-31 21:08 UTC, taylorfturner commented on tests/distinct_generators/test_datetime_generator.py
> +        )
move to L35 function and rename L35 function

2023-07-31 21:08 UTC, taylorfturner commented on tests/distinct_generators/test_datetime_generator.py
>                  self.fail("pd.to_datetime() raised ValueError for default formatting")
not sure this is needed

2023-07-31 21:08 UTC, taylorfturner commented on tests/distinct_generators/test_datetime_generator.py
>          self.assertGreater(sum(format_success), 1)
not sure needed

2023-07-31 21:08 UTC, taylorfturner commented on tests/distinct_generators/test_datetime_generator.py
> +        self.assertEqual(self.random_datetimes_output.shape[0], 10)
move to L35 function

2023-07-31 21:08 UTC, taylorfturner commented on tests/distinct_generators/test_datetime_generator.py
>          self.assertTrue(date_obj <= self.end_date)
L35 function?

2023-07-31 21:08 UTC, taylorfturner commented on tests/distinct_generators/test_datetime_generator.py
>              self.fail("pd.to_datetime() raised ValueError for custom formatting")
needed?

2023-07-31 21:11 UTC, taylorfturner commented on tests/test_dataset_generator.py
> +        df = dataset_generator.generate_dataset(
```suggestion
        actual_df = dataset_generator.generate_dataset(
```

2023-07-31 21:35 UTC, taylorfturner requested changes

2023-07-31 21:35 UTC, taylorfturner commented on tests/test_dataset_generator.py
> +    def test_get_ordered_column(self):
remove this entirely

2023-08-01 11:22 UTC, micdavis submitted a review, later dismissed

2023-08-01 12:57 UTC, taylorfturner requested changes

2023-08-01 12:57 UTC, taylorfturner commented on tests/test_dataset_generator.py
> +        expected = np.array(
it looks like the other tests in `TestGetOrderedColumn` are trying to test `get_ordered_column` which returns an array of strings... but the expected values defined in the test aren't arrays of strings...

2023-08-01 12:57 UTC, taylorfturner commented on tests/test_dataset_generator.py
> +        expected = np.array(
the other tests have the expected of `[:,0]` here but not this test when the test are only changing from `ascending` to `descending`? Do we need `datetime.strptime("2018 09 27", custom_date_format[0]),` values in the `expected` array defined on 340?

2023-08-01 12:57 UTC, taylorfturner commented on tests/test_dataset_generator.py
> +        self.assertTrue(actual_df.equals(expected_df))
just for consistency and readability.... I would change this to `np.testing.assert_array_equals(actual_df.values, expected_df.values)`

2023-08-01 14:27 UTC, taylorfturner requested changes

2023-08-01 14:27 UTC, taylorfturner commented on tests/test_dataset_generator.py
> +        np.testing.assert_array_equal(actual_df, expected_df)
```suggestion
        np.testing.assert_array_equal(actual_df.values, expected_df.values)
```

2023-08-01 14:27 UTC, taylorfturner commented on tests/test_dataset_generator.py
> +pass
remove

2023-08-01 14:33 UTC, taylorfturner approved these changes

2023-08-01 15:24 UTC, micdavis approved these changes

2023-08-01 15:24 UTC, merged